name: Bionic Build
on: 
  push:
    paths-ignore:
      - 'datasets/**'
      - 'docs/**'
      - 'matlab/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'datasets/**'
      - 'docs/**'
      - 'matlab/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  # enable manual trigger
  workflow_dispatch:
  schedule:
    # run on first day of the month
    - cron: '0 0 1 * *'
jobs:
  Bionic-Build:
    runs-on: ubuntu-18.04
    steps:
      # checkout repo
      - name: checkout
        uses: actions/checkout@v2
      # install dependencies
      - name: install dependencies
        run: ./InstallDependencies.bash
        shell: bash
      # build & install libRSF
      - name: create build directory
        run: mkdir build
      - name: run cmake
        working-directory: build
        run: cmake -DLIBRSF_BUILD_TEST=on ..
      - name: run make
        working-directory: build
        run: make all -j$(getconf _NPROCESSORS_ONLN)
      - name: run make install
        working-directory: build
        run: sudo make install
      # upload build as artifact
      - name: upload build as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: build
          path: build/
      # uninstall libRSF
      - name: run make uninstall
        working-directory: build
        run: sudo make uninstall
      

