name: Bionic Tests
on:
  workflow_run:
    workflows: ["Bionic Build"]
    types: 
      - completed
  workflow_dispatch:
jobs:
  Bionic-Tests:
    runs-on: ubuntu-18.04
    steps:
      # checkout repo
      - name: checkout
        uses: actions/checkout@v2
      # download build artifact
      # errors if build workflow was not completed successfully
      - name: download build aritfact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: 'Bionic Build.yml'
          workflow_conclusion: success
          name: build
          path: build/
      # make tests executable
      - name: 'make tests executable'
        run: 'chmod -R 755 build/test' 
      # install dependencies
      - name: install dependencies
        run: ./InstallDependencies.bash
        shell: bash
      # run tests
      - name: 'run tests'
        working-directory: build
        run: 'make test'