name: Bionic Build
on: 
  push:
    paths-ignore:
      - 'datasets/**'
      - 'docs/**'
      - 'matlab/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'datasets/**'
      - 'docs/**'
      - 'matlab/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  # enable manual trigger
  workflow_dispatch:
  schedule:
    # run on first day of the month
    - cron: '0 0 1 * *'
jobs:
  Bionic-Build:
    runs-on: ubuntu-18.04
    steps:
      # checkout repo
      - name: checkout
        uses: actions/checkout@v2
      # install dependencies
      - name: Install dependencies
        run: ./InstallDependencies.bash
        shell: bash
      # build & install libRSF
      - name: Build lib
        run: ./Build.bash
        shell: bash 
      - name: Install lib
        working-directory: build
        run: sudo make install
      # uninstall libRSF
      - name: Uninstall lib
        working-directory: build
        run: sudo make uninstall
      

