name: Bionic Tests
on:
  workflow_run:
    workflows: ["Bionic Build"]
    types: 
      - completed
  workflow_dispatch:
jobs:
  Bionic-Tests:
    runs-on: ubuntu-18.04
    steps:
      # checkout repo
      - name: checkout
        uses: actions/checkout@v2
      # install dependencies
      - name: install dependencies
        run: ./InstallDependencies.bash
        shell: bash
      # build libRSF
      - name: create build directory
        run: mkdir build
      - name: run cmake
        working-directory: build
        run: cmake -DLIBRSF_BUILD_TEST=on ..
      - name: run make
        working-directory: build
        run: make all -j$(getconf _NPROCESSORS_ONLN)
      # run tests
      - name: 'run tests'
        working-directory: build
        run: 'make test'