name: buildAndRunExamples2004
on: [push]
jobs:
  buildAndRunExamples2004:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install dependencies
        run: bash InstallDependencies.bash
      - name: create build directory
        run: mkdir build
      - name: run cmake
        working-directory: build
        run: cmake ..
      - name: run make
        working-directory: build
        run: make all -j$(getconf _NPROCESSORS_ONLN)
      - name: run make install
        working-directory: build
        run: sudo make install
      - name: make exampleResults directory for examples output
        run: mkdir exampleResults
      - name: run ICRA 2019 Application
        run: 'build/applications/ICRA19_GNSS datasets/smartLoc/Berlin_Potsdamer_Platz_Input.txt exampleResults/Result_Berlin_Potsdamer_Platz_Web.txt error: gauss'
      - name: upload exampleResults as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: exampleResults
          path: exampleResults/
      - name: run make uninstall
        working-directory: build
        run: sudo make uninstall
      

